<?php

namespace Database\Seeders;

use App\Models\AmenitiesCheck;
use Illuminate\Database\Seeder;

class AmenitiesCheckSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $amenitiesChecks = [
            ['name' =>'Acepta mascotas', 'amenities_id' => 1],
            ['name' =>'Piscina', 'amenities_id' => 1],
            ['name' =>'Garaje', 'amenities_id' => 1],
            ['name' =>'Gimnasio', 'amenities_id' => 1],
            ['name' =>'Parqueadero subterraneo', 'amenities_id' => 1],
            ['name' =>'En construcción', 'amenities_id' => 1],
            ['name' => 'Parrilla', 'amenities_id' => 1],
            ['name' => 'Apto estudiantes', 'amenities_id' => 1],
            ['name' => 'Luminoso', 'amenities_id' => 1],
            ['name' => 'Apto profesional', 'amenities_id' => 1],
            ['name' => 'Solarium', 'amenities_id' => 1],
            ['name' => 'Parqueadero', 'amenities_id' => 1],
            ['name' => 'Planos aprobados', 'amenities_id' => 1],
            ['name' => 'Apto Crédito', 'amenities_id' => 1],
            ['name' => 'Entrada para Auto', 'amenities_id' => 1],
            ['name' => 'Cocina Amoblada', 'amenities_id' => 1],
            ['name' => 'Vista al Rio', 'amenities_id' => 1],
            ['name' => 'Muros Perimetrales', 'amenities_id' => 1],
            ['name' => 'Medidor Eléctrico Individual', 'amenities_id' => 1],
            ['name' => 'Barrio Cerrado', 'amenities_id' => 1],
            ['name' => 'Garita de Seguridad', 'amenities_id' => 1],
            ['name' => 'Piscina Cerrada', 'amenities_id' => 1],
            ['name' => 'Facilidades Movilidad Reducida', 'amenities_id' => 1],
            ['name' => 'Agua Corriente', 'amenities_id' => 2],
            ['name' => 'Claocas', 'amenities_id' => 2],
            ['name' => 'Electricidad', 'amenities_id' => 2],
            ['name' => 'Tendido Eléctrico', 'amenities_id' => 2],
            ['name' => 'Red de Gas Natural', 'amenities_id' => 2],
            ['name' => 'nicho para Gas', 'amenities_id' => 2],
            ['name' => 'Galeria Techada', 'amenities_id' => 2],
            ['name' => 'TV por Cable', 'amenities_id' => 2],
            ['name' => 'Internet / Wifi', 'amenities_id' => 2],
            ['name' => 'Televisión', 'amenities_id' => 2],
            ['name' => 'Estacionamiento Autos Techado', 'amenities_id' => 2],
            ['name' => 'Equipo Música', 'amenities_id' => 2],
            ['name' => 'Ropa de Cama', 'amenities_id' => 2],
            ['name' => 'Frazadas y Cobertores', 'amenities_id' => 2],
            ['name' => 'Balcón', 'amenities_id' => 3],
            ['name' => 'Patio', 'amenities_id' => 3],
            ['name' => 'Comedor', 'amenities_id' => 3],
            ['name' => 'Terraza', 'amenities_id' => 3],
            ['name' => 'Dependencia de Servicio', 'amenities_id' => 3],
            ['name' => 'Balcón Terraza', 'amenities_id' => 3],
            ['name' => 'Aire Acondicionado', 'amenities_id' => 4],
            ['name' => 'Amoblado', 'amenities_id' => 4],
            ['name' => 'Alarma', 'amenities_id' => 4],
            ['name' => 'Calefacción', 'amenities_id' => 4],
            ['name' => 'Calefacción Central / Piso Radiente / Radiadores', 'amenities_id' => 4],
            ['name' => 'Quincho', 'amenities_id' => 4],
            ['name' => 'Cerca de Escuelas', 'amenities_id' => 4],
            ['name' => 'Calefacción Centralizada', 'amenities_id' => 4],
            ['name' => 'Calefactor a Gas', 'amenities_id' => 4],
            ['name' => 'Alumbrado Público', 'amenities_id' => 4],
            ['name' => 'Asfalto', 'amenities_id' => 4],
            ['name' => 'Ventiladores de Techo', 'amenities_id' => 4],
            ['name' => 'Microondas', 'amenities_id' => 4],
            ['name' => 'Lavavajillas', 'amenities_id' => 4],
            ['name' => 'Lavaropas', 'amenities_id' => 4],
            ['name' => 'Secarropa', 'amenities_id' => 4],
            ['name' => 'Grupo eletrógeno', 'amenities_id' => 4],
            ['name' => 'Servicios Compratidos', 'amenities_id' => 5],
            ['name' => 'Portones eléctricos', 'amenities_id' => 6],
            ['name' => 'Seguridad 24hs.', 'amenities_id' => 6],
            ['name' => 'Terreno Plano', 'amenities_id' => 7],
            ['name' => 'Piscina', 'amenities_id' => 7],
            ['name' => 'Sauna', 'amenities_id' => 7],
            ['name' => 'Bosque', 'amenities_id' => 7],
            ['name' => 'Acepta mascotas', 'amenities_id' => 1],
            ['name' => 'Piscina', 'amenities_id' => 1],
            ['name' => 'Garaje', 'amenities_id' => 1],
            ['name' => 'Gimnasio', 'amenities_id' => 1],
            ['name' => 'Parqueadero subterraneo', 'amenities_id' => 1],
            ['name' => 'En construcción', 'amenities_id' => 1],
            ['name' => 'Parrilla', 'amenities_id' => 1],
            ['name' => 'Apto estudiantes', 'amenities_id' => 1],
            ['name' => 'Luminoso', 'amenities_id' => 1],
            ['name' => 'Apto profesional', 'amenities_id' => 1],
            ['name' => 'Solarium', 'amenities_id' => 1],
            ['name' => 'Parqueadero', 'amenities_id' => 1],
            ['name' => 'Planos aprobados', 'amenities_id' => 1],
            ['name' => 'Apto Crédito', 'amenities_id' => 1],
            ['name' => 'Entrada para Auto', 'amenities_id' => 1],
            ['name' => 'Cocina Amoblada', 'amenities_id' => 1],
            ['name' => 'Vista al Rio', 'amenities_id' => 1],
            ['name' => 'Muros Perimetrales', 'amenities_id' => 1],
            ['name' => 'Medidor Eléctrico Individual', 'amenities_id' => 1],
            ['name' => 'Barrio Cerrado', 'amenities_id' => 1],
            ['name' => 'Garita de Seguridad', 'amenities_id' => 1],
            ['name' => 'Piscina Cerrada', 'amenities_id' => 1],
            ['name' => 'Facilidades Movilidad Reducida', 'amenities_id' => 1],
            ['name' => 'Acepta mascotas', 'amenities_id' => 1],
            ['name' => 'Piscina', 'amenities_id' => 1],
            ['name' => 'Garaje', 'amenities_id' => 1],
            ['name' => 'Gimnasio', 'amenities_id' => 1],
            ['name' => 'Parqueadero subterraneo', 'amenities_id' => 1],
            ['name' => 'En construcción', 'amenities_id' => 1],
            ['name' => 'Parrilla', 'amenities_id' => 1],
            ['name' => 'Apto estudiantes', 'amenities_id' => 1],
            ['name' => 'Luminoso', 'amenities_id' => 1],
            ['name' => 'Apto profesional', 'amenities_id' => 1],
            ['name' => 'Solarium', 'amenities_id' => 1],
            ['name' => 'Parqueadero', 'amenities_id' => 1],
            ['name' => 'Planos aprobados', 'amenities_id' => 1],
            ['name' => 'Apto Crédito', 'amenities_id' => 1],
            ['name' => 'Entrada para Auto', 'amenities_id' => 1],
            ['name' => 'Cocina Amoblada', 'amenities_id' => 1],
            ['name' => 'Vista al Rio', 'amenities_id' => 1],
            ['name' => 'Muros Perimetrales', 'amenities_id' => 1],
            ['name' => 'Medidor Eléctrico Individual', 'amenities_id' => 1],
            ['name' => 'Barrio Cerrado', 'amenities_id' => 1],
            ['name' => 'Garita de Seguridad', 'amenities_id' => 1],
            ['name' => 'Piscina Cerrada', 'amenities_id' => 1],
            ['name' => 'Facilidades Movilidad Reducida', 'amenities_id' => 1],
        ];

        foreach ($amenitiesChecks as $amenitiesChecksData) {
            AmenitiesCheck::create($amenitiesChecksData);
        }
    }
}
