<?php

namespace Database\Seeders;

use App\Models\AmenitiesCheck;
use Illuminate\Database\Seeder;

class AmenitiesCheckSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $amenitiesChecks = [
            ['name' =>'Acepta mascotas', 'amenities_id' => 1],
            ['name' =>'Piscina', 'amenities_id' => 1],
            ['name' =>'Garaje', 'amenities_id' => 1],
            ['name' =>'Gimnasio', 'amenities_id' => 1],
            ['name' =>'Parqueadero subterraneo', 'amenities_id' => 1],
            ['name' =>'En construcción', 'amenities_id' => 1],
            ['name' => 'Parrilla', 'amenities_id' => 1],
            ['name' => 'Apto estudiantes', 'amenities_id' => 1],
            ['name' => 'Luminoso', 'amenities_id' => 1],
            ['name' => 'Apto profesional', 'amenities_id' => 1],
            ['name' => 'Solarium', 'amenities_id' => 1],
            ['name' => 'Parqueadero', 'amenities_id' => 1],
            ['name' => 'Planos aprobados', 'amenities_id' => 1],
            ['name' => 'Apto Crédito', 'amenities_id' => 1],
            ['name' => 'Entrada para Auto', 'amenities_id' => 1],
            ['name' => 'Cocina Amoblada', 'amenities_id' => 1],
            ['name' => 'Vista al Rio', 'amenities_id' => 1],
            ['name' => 'Muros Perimetrales', 'amenities_id' => 1],
            ['name' => 'Medidor Eléctrico Individual', 'amenities_id' => 1],
            ['name' => 'Barrio Cerrado', 'amenities_id' => 1],
            ['name' => 'Garita de Seguridad', 'amenities_id' => 1],
            ['name' => 'Piscina Cerrada', 'amenities_id' => 1],
            ['name' => 'Facilidades Movilidad Reducida', 'amenities_id' => 1],
            ['name' => 'Agua Corriente', 2],
            ['name' => 'Claocas', 2],
            ['name' => 'Electricidad', 2],
            ['name' => 'Tendido Eléctrico', 2],
            ['name' => 'Red de Gas Natural', 2],
            ['name' => 'nicho para Gas', 2],
            ['name' => 'Galeria Techada', 2],
            ['name' => 'TV por Cable', 2],
            ['name' => 'Internet / Wifi', 2],
            ['name' => 'Televisión', 2],
            ['name' => 'Estacionamiento Autos Techado', 2],
            ['name' => 'Equipo Música', 2],
            ['name' => 'Ropa de Cama', 2],
            ['name' => 'Frazadas y Cobertores', 2],
            ['name' => 'Balcón', 3],
            ['name' => 'Patio', 3],
            ['name' => 'Comedor', 3],
            ['name' => 'Terraza', 3],
            ['name' => 'Dependencia de Servicio', 3],
            ['name' => 'Balcón Terraza', 3],
            ['name' => 'Aire Acondicionado', 4],
            ['name' => 'Amoblado', 4],
            ['name' => 'Alarma', 4],
            ['name' => 'Calefacción', 4],
            ['name' => 'Calefacción Central / Piso Radiente / Radiadores', 4],
            ['name' => 'Quincho', 4],
            ['name' => 'Cerca de Escuelas', 4],
            ['name' => 'Calefacción Centralizada', 4],
            ['name' => 'Calefactor a Gas', 4],
            ['name' => 'Alumbrado Público', 4],
            ['name' => 'Asfalto', 4],
            ['name' => 'Ventiladores de Techo', 4],
            ['name' => 'Microondas', 4],
            ['name' => 'Lavavajillas', 4],
            ['name' => 'Lavaropas', 4],
            ['name' => 'Secarropa', 4],
            ['name' => 'Grupo eletrógeno', 4],
            ['name' => 'Servicios Compratidos', 5],
            ['name' => 'Portones eléctricos', 6],
            ['name' => 'Seguridad 24hs.', 6],
            ['name' => 'Terreno Plano', 7],
            ['name' => 'Piscina', 7],
            ['name' => 'Sauna', 7],
            ['name' => 'Bosque', 7],
            ['name' => 'Acepta mascotas', 'amenities_id' => 1],
            ['name' => 'Piscina', 'amenities_id' => 1],
            ['name' => 'Garaje', 'amenities_id' => 1],
            ['name' => 'Gimnasio', 'amenities_id' => 1],
            ['name' => 'Parqueadero subterraneo', 'amenities_id' => 1],
            ['name' => 'En construcción', 'amenities_id' => 1],
            ['name' => 'Parrilla', 'amenities_id' => 1],
            ['name' => 'Apto estudiantes', 'amenities_id' => 1],
            ['name' => 'Luminoso', 'amenities_id' => 1],
            ['name' => 'Apto profesional', 'amenities_id' => 1],
            ['name' => 'Solarium', 'amenities_id' => 1],
            ['name' => 'Parqueadero', 'amenities_id' => 1],
            ['name' => 'Planos aprobados', 'amenities_id' => 1],
            ['name' => 'Apto Crédito', 'amenities_id' => 1],
            ['name' => 'Entrada para Auto', 'amenities_id' => 1],
            ['name' => 'Cocina Amoblada', 'amenities_id' => 1],
            ['name' => 'Vista al Rio', 'amenities_id' => 1],
            ['name' => 'Muros Perimetrales', 'amenities_id' => 1],
            ['name' => 'Medidor Eléctrico Individual', 'amenities_id' => 1],
            ['name' => 'Barrio Cerrado', 'amenities_id' => 1],
            ['name' => 'Garita de Seguridad', 'amenities_id' => 1],
            ['name' => 'Piscina Cerrada', 'amenities_id' => 1],
            ['name' => 'Facilidades Movilidad Reducida', 'amenities_id' => 1],
            ['name' => 'Acepta mascotas', 'amenities_id' => 1],
            ['name' => 'Piscina', 'amenities_id' => 1],
            ['name' => 'Garaje', 'amenities_id' => 1],
            ['name' => 'Gimnasio', 'amenities_id' => 1],
            ['name' => 'Parqueadero subterraneo', 'amenities_id' => 1],
            ['name' => 'En construcción', 'amenities_id' => 1],
            ['name' => 'Parrilla', 'amenities_id' => 1],
            ['name' => 'Apto estudiantes', 'amenities_id' => 1],
            ['name' => 'Luminoso', 'amenities_id' => 1],
            ['name' => 'Apto profesional', 'amenities_id' => 1],
            ['name' => 'Solarium', 'amenities_id' => 1],
            ['name' => 'Parqueadero', 'amenities_id' => 1],
            ['name' => 'Planos aprobados', 'amenities_id' => 1],
            ['name' => 'Apto Crédito', 'amenities_id' => 1],
            ['name' => 'Entrada para Auto', 'amenities_id' => 1],
            ['name' => 'Cocina Amoblada', 'amenities_id' => 1],
            ['name' => 'Vista al Rio', 'amenities_id' => 1],
            ['name' => 'Muros Perimetrales', 'amenities_id' => 1],
            ['name' => 'Medidor Eléctrico Individual', 'amenities_id' => 1],
            ['name' => 'Barrio Cerrado', 'amenities_id' => 1],
            ['name' => 'Garita de Seguridad', 'amenities_id' => 1],
            ['name' => 'Piscina Cerrada', 'amenities_id' => 1],
            ['name' => 'Facilidades Movilidad Reducida', 'amenities_id' => 1],
        ];

        foreach ($amenitiesChecks as $amenitiesChecksData) {
            AmenitiesCheck::create($amenitiesChecksData);
        }
    }
}
