<?php

namespace Database\Seeders;

use App\Models\Ciudades;
use Illuminate\Database\Seeder;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ciudades = [
            ['name' => 'Puerto Ayacucho', 'estado_id' => 1],
            ['name' => 'San Fernando de Atabapo', 'estado_id' => 1],
            ['name' => 'Isla Ratón', 'estado_id' => 1],
            ['name' => 'San Juan de Manapiare', 'estado_id' => 1],
            ['name' => 'Maroa', 'estado_id' => 1],
            ['name' => 'San Carlos de Río Negro', 'estado_id' => 1],
            ['name' => 'La Esmeralda', 'estado_id' => 1],
            ['name' => 'Barcelona', 'estado_id' => 2],
            ['name' => 'Puerto La Cruz', 'estado_id' => 2],
            ['name' => 'Lechería', 'estado_id' => 2],
            ['name' => 'El Tigre', 'estado_id' => 2],
            ['name' => 'Anaco', 'estado_id' => 2],
            ['name' => 'Cantaura', 'estado_id' => 2],
            ['name' => 'San José de Guanipa', 'estado_id' => 2],
            ['name' => 'El Tigrito', 'estado_id' => 2],
            ['name' => 'Clarines', 'estado_id' => 2],
            ['name' => 'Pariaguán', 'estado_id' => 2],
            ['name' => 'Guanta', 'estado_id' => 2],
            ['name' => 'Santa Ana', 'estado_id' => 2],
            ['name' => 'San Mateo', 'estado_id' => 2],
            ['name' => 'El Chaparro', 'estado_id' => 2],
            ['name' => 'Aragua de Barcelona', 'estado_id' => 2],
            ['name' => 'San Fernando de Apure', 'estado_id' => 3],
            ['name' => 'Achaguas', 'estado_id' => 3],
            ['name' => 'El Recreo', 'estado_id' => 3],
            ['name' => 'Elorza', 'estado_id' => 3],
            ['name' => 'El Nula', 'estado_id' => 3],
            ['name' => 'Guasdualito', 'estado_id' => 3],
            ['name' => 'Mantecal', 'estado_id' => 3],
            ['name' => 'Puerto Páez', 'estado_id' => 3],
            ['name' => 'Biruaca', 'estado_id' => 3],
            ['name' => 'Bruzual', 'estado_id' => 3],
            ['name' => 'San Juan de Payara', 'estado_id' => 3],
            ['name' => 'San Rafael de Atamaica', 'estado_id' => 3],
            ['name' => 'La Victoria de Acentejo', 'estado_id' => 3],
            ['name' => 'San Fernando de Atabapo', 'estado_id' => 3],
            ['name' => 'San Gabriel de Tucupido', 'estado_id' => 3],
            ['name' => 'Maracay', 'estado_id' => 4],
            ['name' => 'Turmero', 'estado_id' => 4],
            ['name' => 'Cagua', 'estado_id' => 4],
            ['name' => 'La Victoria', 'estado_id' => 4],
            ['name' => 'El Limón', 'estado_id' => 4],
            ['name' => 'Palo Negro', 'estado_id' => 4],
            ['name' => 'Villa de Cura', 'estado_id' => 4],
            ['name' => 'Santa Rita', 'estado_id' => 4],
            ['name' => 'San Mateo', 'estado_id' => 4],
            ['name' => 'El Consejo', 'estado_id' => 4],
            ['name' => 'San Sebastián', 'estado_id' => 4],
            ['name' => 'Las Tejerías', 'estado_id' => 4],
            ['name' => 'Santa Cruz', 'estado_id' => 4],
            ['name' => 'La Colonia Tovar', 'estado_id' => 4],
            ['name' => 'Ocumare de la Costa', 'estado_id' => 4],
            ['name' => 'Barinas', 'estado_id' => 5],
            ['name' => 'Socopó', 'estado_id' => 5],
            ['name' => 'Ciudad Bolivia', 'estado_id' => 5],
            ['name' => 'Barinitas', 'estado_id' => 5],
            ['name' => 'Santa Bárbara', 'estado_id' => 5],
            ['name' => 'Sabaneta', 'estado_id' => 5],
            ['name' => 'Barrancas', 'estado_id' => 5],
            ['name' => 'Calderas', 'estado_id' => 5],
            ['name' => 'Libertad', 'estado_id' => 5],
            ['name' => 'Obispos', 'estado_id' => 5],
            ['name' => 'Pedraza', 'estado_id' => 5],
            ['name' => 'Rojas', 'estado_id' => 5],
            ['name' => 'Sosa', 'estado_id' => 5],
            ['name' => 'Andrés Eloy Blanco', 'estado_id' => 5],
            ['name' => 'Arismendi', 'estado_id' => 5],
            ['name' => 'Ciudad Bolívar', 'estado_id' => 6],
            ['name' => 'Ciudad Guayana', 'estado_id' => 6],
            ['name' => 'El Callao', 'estado_id' => 6],
            ['name' => 'Caroní', 'estado_id' => 6],
            ['name' => 'Upata', 'estado_id' => 6],
            ['name' => 'Santa Elena de Uairén', 'estado_id' => 6],
            ['name' => 'Tumeremo', 'estado_id' => 6],
            ['name' => 'Puerto Ordaz', 'estado_id' => 6],
            ['name' => 'San Félix', 'estado_id' => 6],
            ['name' => 'Caicara del Orinoco', 'estado_id' => 6],
            ['name' => 'El Dorado', 'estado_id' => 6],
            ['name' => 'Guasipati', 'estado_id' => 6],
            ['name' => 'Ciudad Piar', 'estado_id' => 6],
            ['name' => 'La Paragua', 'estado_id' => 6],
            ['name' => 'San Ignacio de Yuruaní', 'estado_id' => 6],
            ['name' => 'Valencia', 'estado_id' => 7],
            ['name' => 'Puerto Cabello', 'estado_id' => 7],
            ['name' => 'Guacara', 'estado_id' => 7],
            ['name' => 'San Diego', 'estado_id' => 7],
            ['name' => 'Naguanagua', 'estado_id' => 7],
            ['name' => 'Los Guayos', 'estado_id' => 7],
            ['name' => 'Mariara', 'estado_id' => 7],
            ['name' => 'Morón', 'estado_id' => 7],
            ['name' => 'Bejuma', 'estado_id' => 7],
            ['name' => 'San Joaquín', 'estado_id' => 7],
            ['name' => 'Montalbán', 'estado_id' => 7],
            ['name' => 'Miranda', 'estado_id' => 7],
            ['name' => 'Güigüe', 'estado_id' => 7],
            ['name' => 'Tacarigua', 'estado_id' => 7],
            ['name' => 'Libertador', 'estado_id' => 7],
            ['name' => 'San Carlos', 'estado_id' => 8],
            ['name' => 'Tinaquillo', 'estado_id' => 8],
            ['name' => 'Tinaco', 'estado_id' => 8],
            ['name' => 'El Baúl', 'estado_id' => 8],
            ['name' => 'Libertad', 'estado_id' => 8],
            ['name' => 'El Pao', 'estado_id' => 8],
            ['name' => 'Macapo', 'estado_id' => 8],
            ['name' => 'El Amparo', 'estado_id' => 8],
            ['name' => 'Las Vegas', 'estado_id' => 8],
            ['name' => 'El Baulito', 'estado_id' => 8],
            ['name' => 'El Baúl', 'estado_id' => 8],
            ['name' => 'El Socorro', 'estado_id' => 8],
            ['name' => 'La Aguadita', 'estado_id' => 8],
            ['name' => 'La Mesa', 'estado_id' => 8],
            ['name' => 'El Calvario', 'estado_id' => 8],
            ['name' => 'Tucupita', 'estado_id' => 9],
            ['name' => 'Casacoima', 'estado_id' => 9],
            ['name' => 'Antonio Díaz', 'estado_id' => 9],
            ['name' => 'Pedernales', 'estado_id' => 9],
            ['name' => 'Coro', 'estado_id' => 10],
            ['name' => 'Punto Fijo', 'estado_id' => 10],
            ['name' => 'Churuguara', 'estado_id' => 10],
            ['name' => 'Tucacas', 'estado_id' => 10],
            ['name' => 'Judibana', 'estado_id' => 10],
            ['name' => 'Santa Ana de Coro', 'estado_id' => 10],
            ['name' => 'La Vela de Coro', 'estado_id' => 10],
            ['name' => 'Chichiriviche', 'estado_id' => 10],
            ['name' => 'Adícora', 'estado_id' => 10],
            ['name' => 'Cumarebo', 'estado_id' => 10],
            ['name' => 'Dabajuro', 'estado_id' => 10],
            ['name' => 'San Juan de Los Cayos', 'estado_id' => 10],
            ['name' => 'Santa Cruz de Bucaral', 'estado_id' => 10],
            ['name' => 'Tocopero', 'estado_id' => 10],
            ['name' => 'Capatárida', 'estado_id' => 10],
            ['name' => 'San Juan de los Morros', 'estado_id' => 11],
            ['name' => 'Altagracia de Orituco', 'estado_id' => 11],
            ['name' => 'Calabozo', 'estado_id' => 11],
            ['name' => 'Chaguaramas', 'estado_id' => 11],
            ['name' => 'El Socorro', 'estado_id' => 11],
            ['name' => 'Guayabal', 'estado_id' => 11],
            ['name' => 'Ortiz', 'estado_id' => 11],
            ['name' => 'Barquisimeto', 'estado_id' => 12],
            ['name' => 'Cabudare', 'estado_id' => 12],
            ['name' => 'Carora', 'estado_id' => 12],
            ['name' => 'El Tocuyo', 'estado_id' => 12],
            ['name' => 'Quíbor', 'estado_id' => 12],
            ['name' => 'Duaca', 'estado_id' => 12],
            ['name' => 'Sarare', 'estado_id' => 12],
            ['name' => 'Los Rastrojos', 'estado_id' => 12],
            ['name' => 'Sanare', 'estado_id' => 12],
            ['name' => 'Cubiro', 'estado_id' => 12],
            ['name' => 'Mérida', 'estado_id' => 13],
            ['name' => 'El Vigía', 'estado_id' => 13],
            ['name' => 'Tovar', 'estado_id' => 13],
            ['name' => 'Ejido', 'estado_id' => 13],
            ['name' => 'Lagunillas', 'estado_id' => 13],
            ['name' => 'Nueva Bolivia', 'estado_id' => 13],
            ['name' => 'Los Teques', 'estado_id' => 14],
            ['name' => 'Guarenas', 'estado_id' => 14],
            ['name' => 'Guatire', 'estado_id' => 14],
            ['name' => 'Santa Teresa del Tuy', 'estado_id' => 14],
            ['name' => 'Charallave', 'estado_id' => 14],
            ['name' => 'Maturín', 'estado_id' => 15],
            ['name' => 'Punta de Mata', 'estado_id' => 15],
            ['name' => 'Caripito', 'estado_id' => 15],
            ['name' => 'Quiriquire', 'estado_id' => 15],
            ['name' => 'Temblador', 'estado_id' => 15],
            ['name' => 'Porlamar', 'estado_id' => 16],
            ['name' => 'La Asunción', 'estado_id' => 16],
            ['name' => 'Pampatar', 'estado_id' => 16],
            ['name' => 'Juan Griego', 'estado_id' => 16],
            ['name' => 'El Valle del Espíritu Santo', 'estado_id' => 16],
            ['name' => 'Acarigua', 'estado_id' => 17],
            ['name' => 'Guanare', 'estado_id' => 17],
            ['name' => 'Araure', 'estado_id' => 17],
            ['name' => 'Guanarito', 'estado_id' => 17],
            ['name' => 'Agua Blanca', 'estado_id' => 17],
            ['name' => 'Cumaná', 'estado_id' => 18],
            ['name' => 'Carúpano', 'estado_id' => 18],
            ['name' => 'Güiria', 'estado_id' => 18],
            ['name' => 'El Tigre', 'estado_id' => 18],
            ['name' => 'San Antonio del Golfo', 'estado_id' => 18],
            ['name' => 'San Cristóbal', 'estado_id' => 19],
            ['name' => 'San Antonio del Táchira', 'estado_id' => 19],
            ['name' => 'Rubio', 'estado_id' => 19],
            ['name' => 'Ureña', 'estado_id' => 19],
            ['name' => 'La Fría', 'estado_id' => 19],
            ['name' => 'Trujillo', 'estado_id' => 20],
            ['name' => 'Valera', 'estado_id' => 20],
            ['name' => 'Boconó', 'estado_id' => 20],
            ['name' => 'Carvajal', 'estado_id' => 20],
            ['name' => 'Escuque', 'estado_id' => 20],
            ['name' => 'La Guaira', 'estado_id' => 21],
            ['name' => 'Maiquetía', 'estado_id' => 21],
            ['name' => 'Catia La Mar', 'estado_id' => 21],
            ['name' => 'Macuto', 'estado_id' => 21],
            ['name' => 'Caraballeda', 'estado_id' => 21],
            ['name' => 'San Felipe', 'estado_id' => 22],
            ['name' => 'Chivacoa', 'estado_id' => 22],
            ['name' => 'Nirgua', 'estado_id' => 22],
            ['name' => 'Yaritagua', 'estado_id' => 22],
            ['name' => 'Independencia', 'estado_id' => 22],
            ['name' => 'Maracaibo', 'estado_id' => 23],
            ['name' => 'Cabimas', 'estado_id' => 23],
            ['name' => 'Ciudad Ojeda', 'estado_id' => 23],
            ['name' => 'San Francisco', 'estado_id' => 23],
            ['name' => 'Machiques', 'estado_id' => 23],
            ['name' => 'Caracas', 'estado_id' => 24],
            ['name' => 'Los Monjes', 'estado_id' => 25],
            ['name' => 'Los Hermanos', 'estado_id' => 25],
            ['name' => 'Los Frailes', 'estado_id' => 25],
            ['name' => 'Isla de Aves', 'estado_id' => 25],
            ['name' => 'La Sola', 'estado_id' => 25],
            ['name' => 'La Tortuga', 'estado_id' => 25],
            ['name' => 'La Blanquilla', 'estado_id' => 25],

        ];

        
        foreach ($ciudades as $ciudadesData) {
            $ciudades = Ciudades::create($ciudadesData);
        }
    }
}
